### ISSUE TITLE
usage instruction

### ISSUE THREAD

**Issue by exceter** [jwoglom/dm2nsc#1]
Hi,
can you make instruction how to use the script?
I use Diabetes-M and xdrip+ via nightscout and want to use sync them. There is now nightscout sync to Diabetes-M, but looking for another direction as well which would be very helpful.

**Comment by jwoglom** [comment]
Hi, I added a bit more information in the README about how to set the project up. It's a fairly simple Python3 script you can run manually or in a cronjob/scheduled task; just install the dependencies and create a `secret.py` as described and you should be good to go.

There's a section in `getdata.py` where you can add some custom processing in the conversion from Diabetes-M data format to Nightscout format; e.x., if you're also doing a sync from nightscout to D-M, you likely will want to exclude that data from being re-imported back into Nightscout (This seems to be denoted by a `"[Nightscout]"` present at the end of the "notes" field in the D-M entry, you'd want to check for that and if so not append the dictionary to the list.)

**Comment by exceter** [comment]
tnx.
i compiled and zipped with all required libs, and uploaded to Azure, created cronjob in WebJobs.
While running it gives following error, can you please suggest:

[03/27/2018 17:26:47 > 4a12dc: SYS INFO] Status changed to Initializing
[03/27/2018 17:26:53 > 4a12dc: SYS INFO] Run script 'getdata.py' with script host - 'PythonScriptHost'
[03/27/2018 17:26:53 > 4a12dc: SYS INFO] Status changed to Running
[03/27/2018 17:26:57 > 4a12dc: ERR ] Traceback (most recent call last):
[03/27/2018 17:26:57 > 4a12dc: ERR ]   File "getdata.py", line 1, in <module>
[03/27/2018 17:26:57 > 4a12dc: ERR ]     import requests, json, arrow, hashlib, urllib, datetime
[03/27/2018 17:26:57 > 4a12dc: ERR ]   File "D:\local\Temp\jobs\triggered\dm2nsc\px5nyp1g.kss\dm2nsc\arrow\__init__.py", line 3, in <module>
[03/27/2018 17:26:57 > 4a12dc: ERR ]     from .arrow import Arrow
[03/27/2018 17:26:57 > 4a12dc: ERR ]   File "D:\local\Temp\jobs\triggered\dm2nsc\px5nyp1g.kss\dm2nsc\arrow\arrow.py", line 19, in <module>
[03/27/2018 17:26:57 > 4a12dc: ERR ]     from arrow import util, locales, parser, formatter
[03/27/2018 17:26:57 > 4a12dc: ERR ]   File "D:\local\Temp\jobs\triggered\dm2nsc\px5nyp1g.kss\dm2nsc\arrow\parser.py", line 12, in <module>
[03/27/2018 17:26:57 > 4a12dc: ERR ]     from backports.functools_lru_cache import lru_cache  # pragma: no cover
[03/27/2018 17:26:57 > 4a12dc: ERR ] ImportError: No module named backports.functools_lru_cache
[03/27/2018 17:26:57 > 4a12dc: SYS INFO] Status changed to Failed
[03/27/2018 17:26:57 > 4a12dc: SYS ERR ] Job failed due to exit code 1

**Comment by jwoglom** [comment]
Are you running the script in python 2.x or 3.x? Per https://github.com/matplotlib/matplotlib/issues/9344, it looks like this `ImportError: No module named backports.functools_lru_cache` exception might be caused by running the script as Python 2. Make sure you're using python 3.x.

**Comment by exceter** [comment]
Thanks a lot. By default on Azure it was version 2.x, after changing to 3.4 script is running.
just faced issue uploading line 44 - notes = entry["notes"]. Just disabled this line by now, later will try to check why so.
